language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
before_script:
  - npm prune
script:
  - npm run lint
  - npm run test
after_success:
  - npm run coverage
  - cat coverage/lcov.info | ./node_modules/.bin/coveralls
