language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
env:
  - TASK=lint
  - TASK=test
before_script:
  - npm prune
script: "npm run $TASK"
after_success:
  - npm run coverage
  - cat coverage/lcov.info | ./node_modules/.bin/coveralls
